import Typography from '@mui/material/Typography';
import Avatar from '@mui/material/Avatar';
import Button from '@mui/material/Button';
import { Link } from 'react-router-dom';

import S from './profile-view.style';
import { ProfileViewProps } from './profile-view.types';

/**
 * design spec generated by AI: https://v0.dev/r/cNDG5ixHWXH
 * @param props
 * @returns
 */
export function ProfileView(props: ProfileViewProps) {
  const { profile } = props;
  return (
    <S.ProfileView>
      <Avatar alt={`${profile.username} avatar`} src={profile.avatar} sx={{ width: 120, height: 120 }} />
      <Typography variant="h3">
        {profile.firstName} {profile.lastName}
      </Typography>

      <Typography variant="body1">{profile.bio}</Typography>

      <Link to="/profile/me/edit">
        <Button variant="outlined" sx={{ marginTop: 3 }}>
          Edit Profile
        </Button>
      </Link>
    </S.ProfileView>
  );
}
