interface Window {
  blocklet: Blocklet;
}

/**
 * Blocklet
 * generated by vscode extension JSON to TS
 */
interface Blocklet {
  CHAIN_TYPE: string;
  appId: string;
  appPid: string;
  appName: string;
  appDescription: string;
  appUrl: string;
  isComponent: boolean;
  alsoKnownAs: any[];
  passportColor: string;
  trustedFactories: any[];
  serverVersion: string;
  prefix: string;
  groupPrefix: string;
  pageGroup: string;
  version: string;
  componentId: string;
  did: string;
  appLogo: string;
  appLogoRect: string;
  webWalletUrl: string;
  preferences: Preferences;
  serverDid: string;
  languages: Language[];
  settings: Settings;
  navigation: Navigation[];
  componentMountPoints: ComponentMountPoint[];
}

interface ComponentMountPoint {
  title: string;
  name: string;
  did: string;
  status: string;
  mountPoint: string;
  components: any[];
}

interface Navigation {
  id: string;
  from: string;
  title: Title | string;
  role: string[];
  section: string[];
  link: string;
  items?: Item[];
  icon?: string;
}

interface Item {
  id: string;
  from: string;
  title: Title;
  icon: string;
  link: string;
}

interface Title {
  en: string;
  zh: string;
}

interface Settings {
  session: Session;
  federated: Federated;
  oauth: Preferences;
}

interface Federated {
  master: Preferences;
  config: Preferences;
}

interface Session {
  ttl: number;
  cacheTtl: number;
}

interface Language {
  code: string;
  name: string;
}

interface Preferences {}
